# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zhong/ComputerScience/CS121/logistic-regression-sgd

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zhong/ComputerScience/CS121/logistic-regression-sgd

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/zhong/clion-2018.2.6/bin/cmake/linux/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhong/ComputerScience/CS121/logistic-regression-sgd/CMakeFiles /home/zhong/ComputerScience/CS121/logistic-regression-sgd/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhong/ComputerScience/CS121/logistic-regression-sgd/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test4

# Build rule for target.
test4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test4
.PHONY : test4

# fast build rule for target.
test4/fast:
	$(MAKE) -f CMakeFiles/test4.dir/build.make CMakeFiles/test4.dir/build
.PHONY : test4/fast

#=============================================================================
# Target rules for targets named LogisticRegression

# Build rule for target.
LogisticRegression: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LogisticRegression
.PHONY : LogisticRegression

# fast build rule for target.
LogisticRegression/fast:
	$(MAKE) -f CMakeFiles/LogisticRegression.dir/build.make CMakeFiles/LogisticRegression.dir/build
.PHONY : LogisticRegression/fast

#=============================================================================
# Target rules for targets named LogisticRegressionHogwild

# Build rule for target.
LogisticRegressionHogwild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LogisticRegressionHogwild
.PHONY : LogisticRegressionHogwild

# fast build rule for target.
LogisticRegressionHogwild/fast:
	$(MAKE) -f CMakeFiles/LogisticRegressionHogwild.dir/build.make CMakeFiles/LogisticRegressionHogwild.dir/build
.PHONY : LogisticRegressionHogwild/fast

#=============================================================================
# Target rules for targets named LogisticRegressionMiniBatch

# Build rule for target.
LogisticRegressionMiniBatch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LogisticRegressionMiniBatch
.PHONY : LogisticRegressionMiniBatch

# fast build rule for target.
LogisticRegressionMiniBatch/fast:
	$(MAKE) -f CMakeFiles/LogisticRegressionMiniBatch.dir/build.make CMakeFiles/LogisticRegressionMiniBatch.dir/build
.PHONY : LogisticRegressionMiniBatch/fast

#=============================================================================
# Target rules for targets named test2

# Build rule for target.
test2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test2
.PHONY : test2

# fast build rule for target.
test2/fast:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/build
.PHONY : test2/fast

#=============================================================================
# Target rules for targets named LogisticRegressionHogBatch

# Build rule for target.
LogisticRegressionHogBatch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LogisticRegressionHogBatch
.PHONY : LogisticRegressionHogBatch

# fast build rule for target.
LogisticRegressionHogBatch/fast:
	$(MAKE) -f CMakeFiles/LogisticRegressionHogBatch.dir/build.make CMakeFiles/LogisticRegressionHogBatch.dir/build
.PHONY : LogisticRegressionHogBatch/fast

#=============================================================================
# Target rules for targets named test3

# Build rule for target.
test3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test3
.PHONY : test3

# fast build rule for target.
test3/fast:
	$(MAKE) -f CMakeFiles/test3.dir/build.make CMakeFiles/test3.dir/build
.PHONY : test3/fast

#=============================================================================
# Target rules for targets named test1

# Build rule for target.
test1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test1
.PHONY : test1

# fast build rule for target.
test1/fast:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/build
.PHONY : test1/fast

LogisticRegression.o: LogisticRegression.cpp.o

.PHONY : LogisticRegression.o

# target to build an object file
LogisticRegression.cpp.o:
	$(MAKE) -f CMakeFiles/LogisticRegression.dir/build.make CMakeFiles/LogisticRegression.dir/LogisticRegression.cpp.o
	$(MAKE) -f CMakeFiles/LogisticRegressionHogwild.dir/build.make CMakeFiles/LogisticRegressionHogwild.dir/LogisticRegression.cpp.o
	$(MAKE) -f CMakeFiles/LogisticRegressionMiniBatch.dir/build.make CMakeFiles/LogisticRegressionMiniBatch.dir/LogisticRegression.cpp.o
	$(MAKE) -f CMakeFiles/LogisticRegressionHogBatch.dir/build.make CMakeFiles/LogisticRegressionHogBatch.dir/LogisticRegression.cpp.o
.PHONY : LogisticRegression.cpp.o

LogisticRegression.i: LogisticRegression.cpp.i

.PHONY : LogisticRegression.i

# target to preprocess a source file
LogisticRegression.cpp.i:
	$(MAKE) -f CMakeFiles/LogisticRegression.dir/build.make CMakeFiles/LogisticRegression.dir/LogisticRegression.cpp.i
	$(MAKE) -f CMakeFiles/LogisticRegressionHogwild.dir/build.make CMakeFiles/LogisticRegressionHogwild.dir/LogisticRegression.cpp.i
	$(MAKE) -f CMakeFiles/LogisticRegressionMiniBatch.dir/build.make CMakeFiles/LogisticRegressionMiniBatch.dir/LogisticRegression.cpp.i
	$(MAKE) -f CMakeFiles/LogisticRegressionHogBatch.dir/build.make CMakeFiles/LogisticRegressionHogBatch.dir/LogisticRegression.cpp.i
.PHONY : LogisticRegression.cpp.i

LogisticRegression.s: LogisticRegression.cpp.s

.PHONY : LogisticRegression.s

# target to generate assembly for a file
LogisticRegression.cpp.s:
	$(MAKE) -f CMakeFiles/LogisticRegression.dir/build.make CMakeFiles/LogisticRegression.dir/LogisticRegression.cpp.s
	$(MAKE) -f CMakeFiles/LogisticRegressionHogwild.dir/build.make CMakeFiles/LogisticRegressionHogwild.dir/LogisticRegression.cpp.s
	$(MAKE) -f CMakeFiles/LogisticRegressionMiniBatch.dir/build.make CMakeFiles/LogisticRegressionMiniBatch.dir/LogisticRegression.cpp.s
	$(MAKE) -f CMakeFiles/LogisticRegressionHogBatch.dir/build.make CMakeFiles/LogisticRegressionHogBatch.dir/LogisticRegression.cpp.s
.PHONY : LogisticRegression.cpp.s

LogisticRegression_learn.o: LogisticRegression_learn.cpp.o

.PHONY : LogisticRegression_learn.o

# target to build an object file
LogisticRegression_learn.cpp.o:
	$(MAKE) -f CMakeFiles/LogisticRegression.dir/build.make CMakeFiles/LogisticRegression.dir/LogisticRegression_learn.cpp.o
.PHONY : LogisticRegression_learn.cpp.o

LogisticRegression_learn.i: LogisticRegression_learn.cpp.i

.PHONY : LogisticRegression_learn.i

# target to preprocess a source file
LogisticRegression_learn.cpp.i:
	$(MAKE) -f CMakeFiles/LogisticRegression.dir/build.make CMakeFiles/LogisticRegression.dir/LogisticRegression_learn.cpp.i
.PHONY : LogisticRegression_learn.cpp.i

LogisticRegression_learn.s: LogisticRegression_learn.cpp.s

.PHONY : LogisticRegression_learn.s

# target to generate assembly for a file
LogisticRegression_learn.cpp.s:
	$(MAKE) -f CMakeFiles/LogisticRegression.dir/build.make CMakeFiles/LogisticRegression.dir/LogisticRegression_learn.cpp.s
.PHONY : LogisticRegression_learn.cpp.s

LogisticRegression_learn_hogbatch.o: LogisticRegression_learn_hogbatch.cpp.o

.PHONY : LogisticRegression_learn_hogbatch.o

# target to build an object file
LogisticRegression_learn_hogbatch.cpp.o:
	$(MAKE) -f CMakeFiles/LogisticRegressionHogBatch.dir/build.make CMakeFiles/LogisticRegressionHogBatch.dir/LogisticRegression_learn_hogbatch.cpp.o
.PHONY : LogisticRegression_learn_hogbatch.cpp.o

LogisticRegression_learn_hogbatch.i: LogisticRegression_learn_hogbatch.cpp.i

.PHONY : LogisticRegression_learn_hogbatch.i

# target to preprocess a source file
LogisticRegression_learn_hogbatch.cpp.i:
	$(MAKE) -f CMakeFiles/LogisticRegressionHogBatch.dir/build.make CMakeFiles/LogisticRegressionHogBatch.dir/LogisticRegression_learn_hogbatch.cpp.i
.PHONY : LogisticRegression_learn_hogbatch.cpp.i

LogisticRegression_learn_hogbatch.s: LogisticRegression_learn_hogbatch.cpp.s

.PHONY : LogisticRegression_learn_hogbatch.s

# target to generate assembly for a file
LogisticRegression_learn_hogbatch.cpp.s:
	$(MAKE) -f CMakeFiles/LogisticRegressionHogBatch.dir/build.make CMakeFiles/LogisticRegressionHogBatch.dir/LogisticRegression_learn_hogbatch.cpp.s
.PHONY : LogisticRegression_learn_hogbatch.cpp.s

LogisticRegression_learn_hogwild.o: LogisticRegression_learn_hogwild.cpp.o

.PHONY : LogisticRegression_learn_hogwild.o

# target to build an object file
LogisticRegression_learn_hogwild.cpp.o:
	$(MAKE) -f CMakeFiles/LogisticRegressionHogwild.dir/build.make CMakeFiles/LogisticRegressionHogwild.dir/LogisticRegression_learn_hogwild.cpp.o
.PHONY : LogisticRegression_learn_hogwild.cpp.o

LogisticRegression_learn_hogwild.i: LogisticRegression_learn_hogwild.cpp.i

.PHONY : LogisticRegression_learn_hogwild.i

# target to preprocess a source file
LogisticRegression_learn_hogwild.cpp.i:
	$(MAKE) -f CMakeFiles/LogisticRegressionHogwild.dir/build.make CMakeFiles/LogisticRegressionHogwild.dir/LogisticRegression_learn_hogwild.cpp.i
.PHONY : LogisticRegression_learn_hogwild.cpp.i

LogisticRegression_learn_hogwild.s: LogisticRegression_learn_hogwild.cpp.s

.PHONY : LogisticRegression_learn_hogwild.s

# target to generate assembly for a file
LogisticRegression_learn_hogwild.cpp.s:
	$(MAKE) -f CMakeFiles/LogisticRegressionHogwild.dir/build.make CMakeFiles/LogisticRegressionHogwild.dir/LogisticRegression_learn_hogwild.cpp.s
.PHONY : LogisticRegression_learn_hogwild.cpp.s

LogisticRegression_learn_minibatch.o: LogisticRegression_learn_minibatch.cpp.o

.PHONY : LogisticRegression_learn_minibatch.o

# target to build an object file
LogisticRegression_learn_minibatch.cpp.o:
	$(MAKE) -f CMakeFiles/LogisticRegressionMiniBatch.dir/build.make CMakeFiles/LogisticRegressionMiniBatch.dir/LogisticRegression_learn_minibatch.cpp.o
.PHONY : LogisticRegression_learn_minibatch.cpp.o

LogisticRegression_learn_minibatch.i: LogisticRegression_learn_minibatch.cpp.i

.PHONY : LogisticRegression_learn_minibatch.i

# target to preprocess a source file
LogisticRegression_learn_minibatch.cpp.i:
	$(MAKE) -f CMakeFiles/LogisticRegressionMiniBatch.dir/build.make CMakeFiles/LogisticRegressionMiniBatch.dir/LogisticRegression_learn_minibatch.cpp.i
.PHONY : LogisticRegression_learn_minibatch.cpp.i

LogisticRegression_learn_minibatch.s: LogisticRegression_learn_minibatch.cpp.s

.PHONY : LogisticRegression_learn_minibatch.s

# target to generate assembly for a file
LogisticRegression_learn_minibatch.cpp.s:
	$(MAKE) -f CMakeFiles/LogisticRegressionMiniBatch.dir/build.make CMakeFiles/LogisticRegressionMiniBatch.dir/LogisticRegression_learn_minibatch.cpp.s
.PHONY : LogisticRegression_learn_minibatch.cpp.s

test.o: test.cpp.o

.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) -f CMakeFiles/test4.dir/build.make CMakeFiles/test4.dir/test.cpp.o
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/test.cpp.o
	$(MAKE) -f CMakeFiles/test3.dir/build.make CMakeFiles/test3.dir/test.cpp.o
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i

.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) -f CMakeFiles/test4.dir/build.make CMakeFiles/test4.dir/test.cpp.i
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/test.cpp.i
	$(MAKE) -f CMakeFiles/test3.dir/build.make CMakeFiles/test3.dir/test.cpp.i
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s

.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) -f CMakeFiles/test4.dir/build.make CMakeFiles/test4.dir/test.cpp.s
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/test.cpp.s
	$(MAKE) -f CMakeFiles/test3.dir/build.make CMakeFiles/test3.dir/test.cpp.s
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... test4"
	@echo "... LogisticRegression"
	@echo "... LogisticRegressionHogwild"
	@echo "... LogisticRegressionMiniBatch"
	@echo "... test2"
	@echo "... LogisticRegressionHogBatch"
	@echo "... rebuild_cache"
	@echo "... test3"
	@echo "... test1"
	@echo "... LogisticRegression.o"
	@echo "... LogisticRegression.i"
	@echo "... LogisticRegression.s"
	@echo "... LogisticRegression_learn.o"
	@echo "... LogisticRegression_learn.i"
	@echo "... LogisticRegression_learn.s"
	@echo "... LogisticRegression_learn_hogbatch.o"
	@echo "... LogisticRegression_learn_hogbatch.i"
	@echo "... LogisticRegression_learn_hogbatch.s"
	@echo "... LogisticRegression_learn_hogwild.o"
	@echo "... LogisticRegression_learn_hogwild.i"
	@echo "... LogisticRegression_learn_hogwild.s"
	@echo "... LogisticRegression_learn_minibatch.o"
	@echo "... LogisticRegression_learn_minibatch.i"
	@echo "... LogisticRegression_learn_minibatch.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

